Add overrides for vue3 browser bundle
jspm/overrides pull request #19
Opened 2023-10-17 07:25 UTC by RemiDesgrange

Contributing regarding issue https://github.com/jspm/generator/issues/325

I wonder If we could add the prod build as well, since `vue.esm-browser.js` is a dev build and `vue.esm-browser.prod.js` is the proper prod build.

2023-10-17 17:08 UTC, guybedford commented
Can you please update this not to reformat the entire JSON file and instead just make the relevant diff. If you'd like to propose reformatting, let's make that a separate PR.

2023-10-18 05:05 UTC, RemiDesgrange commented
Sorry... I think my editor did some stuff that I didn't want him to do :-/

2023-10-21 20:59 UTC, guybedford requested changes
Thanks for putting this together. Will be happy to merge once we've got it correct.

I notice the `@vue/runtime-dom` is actually incorrect as an override that you copied for the pattern here, so we should probably just remove that.

2023-10-21 20:59 UTC, guybedford commented on overrides.json
> +        "default": "./index.js"
The structure of overrides is that they are overrides of the `package.json` file itself, therefore this needs to be:

```suggestion
        "exports": {
          "module": "./dist/vue.esm-browser.js",
          "default": "./index.js"
        }
```

Note that if we don't include the former exports though, all other exports will break, so we need to extend the existing exports configuration of:

```
"exports": {
    ".": {
      "import": {
        "types": "./dist/vue.d.mts",
        "node": "./index.mjs",
        "default": "./dist/vue.runtime.esm-bundler.js"
      },
      "require": {
        "types": "./dist/vue.d.ts",
        "default": "./index.js"
      }
    },
    "./server-renderer": {
      "import": {
        "types": "./server-renderer/index.d.mts",
        "default": "./server-renderer/index.mjs"
      },
      "require": {
        "types": "./server-renderer/index.d.ts",
        "default": "./server-renderer/index.js"
      }
    },
    "./compiler-sfc": {
      "import": {
        "types": "./compiler-sfc/index.d.mts",
        "browser": "./compiler-sfc/index.browser.mjs",
        "default": "./compiler-sfc/index.mjs"
      },
      "require": {
        "types": "./compiler-sfc/index.d.ts",
        "browser": "./compiler-sfc/index.browser.js",
        "default": "./compiler-sfc/index.js"
      }
    },
    "./jsx-runtime": {
      "types": "./jsx-runtime/index.d.ts",
      "import": "./jsx-runtime/index.mjs",
      "require": "./jsx-runtime/index.js"
    },
    "./jsx-dev-runtime": {
      "types": "./jsx-runtime/index.d.ts",
      "import": "./jsx-runtime/index.mjs",
      "require": "./jsx-runtime/index.js"
    },
    "./jsx": "./jsx.d.ts",
    "./dist/*": "./dist/*",
    "./package.json": "./package.json",
    "./macros": "./macros.d.ts",
    "./macros-global": "./macros-global.d.ts",
    "./ref-macros": "./ref-macros.d.ts"
  },
```

repeating the entire existing configuration, but with the changes.

2023-10-24 07:27 UTC, RemiDesgrange commented
How do you test this config locally ? installing jspm with a modified version of "overrides" ? I did not see in the packages.json where it was in use.

2023-10-25 17:19 UTC, guybedford commented
The same was you test an npm publish configuration. Publish it and see if it works.

2023-10-30 01:27 UTC, guybedford commented
I added this in https://github.com/jspm/overrides/commit/728d2f8f6c593a559d5630f3bb6e3e43e35b1ae6. Thanks for raising this one.

2023-10-30 01:27 UTC, closed without merging

2023-10-30 06:41 UTC, guybedford commented
I think we shouldn't use the non-runtime build here. Instead I've updated to use the runtime build and also added support for the production version in https://github.com/jspm/overrides/commit/f2faf76b72833221ba50bb1c019a98a28eaf67c1.